version: '3'
services:
  db:
    image: mysql
    volumes:
      - data:/var/lib/mysql
      - ./docker/db/mysql.cnf:/etc/mysql/conf.d/mysql.cnf
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    volumes:
      - .:/myapp
      - bundle:/usr/local/bundle
    ports:
      - "3000:3000"
      - "9292:9292"
    depends_on:
      - db
    tty: true
    # command: bundle exec rails s -p 3000 -b '0.0.0.0'
volumes:
  data:
  bundle:
